while ($true) {
    $now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$now] Запуск анализа с qwq:32b..." -ForegroundColor Cyan

    # Собираем код (исключая node_modules, ограничивая размер)
    $code = Get-ChildItem -Path "C:\Users\Den\Downloads\AFK Game" -Recurse -Include *.js,*.ts,*.json,*.md,*.txt,*.html,*.css -Exclude node_modules,.git,dist,build -ErrorAction SilentlyContinue | Where-Object { $_.FullName -notmatch 'node_modules' } | Get-Content -Raw -ErrorAction SilentlyContinue | Out-String
    if ($code.Length -gt 150000) { $code = $code.Substring(0,150000) + "... (обрезано)" }

    $prompt = @"
Ты — ИИ-инженер, специализирующийся на игровой разработке. Проанализируй код проекта AFK Game.

Выдай строго в формате:

БАГИ (с указанием файла и строки, если возможно):
1. ...
2. ...
3. ...
4. ...
5. ...

УЛУЧШЕНИЯ (с примером кода):
1. ...
2. ...
3. ...
4. ...
5. ...

ТЕХНИЧЕСКИЙ ДОЛГ:
1. ...
2. ...
3. ...

Архитектурные замечания:
1. ...
2. ...
3. ...

Код проекта:
$code
"@

    # Запускаем qwq:32b
    $response = $prompt | ollama run qwq:32b --verbose 2>&1
    $logEntry = @"
`n=== $now ===
$response
----------------------------------------
"@
    Add-Content -Path "C:\Users\Den\Downloads\AFK Game\qwq_analysis_log.txt" -Value $logEntry -Encoding UTF8
    Write-Host "[$now] Анализ завершён. Жду 60 минут..." -ForegroundColor Green
    Start-Sleep -Seconds 3600
}
